### ISSUE TITLE
Gradle dependencies for android integration?

### ISSUE THREAD

**Issue by jackd** [flame-engine/gamepads#49]
Android/kotlin/java/gradle noob here, so apologies in advance: but I'm trying to follow the instructions for [android integration](https://github.com/flame-engine/gamepads?tab=readme-ov-file#android-integration) and I'm getting `unresolved reference` and `overrides nothing` errors. I've tried adding a `dependencies` block to my `app/build.gradle`

```gradle
dependencies {
    implementation "org.flame-engine:gamepads-android:0.1.4"
}
```

but gradle can't find it.

Am I missing something? Is there an example with android integration that I can look at somewhere?

Thanks in advance.

**Comment by spydon** [comment]
This example should run on android:
https://github.com/flame-engine/gamepads/tree/main/packages/gamepads/example

**Comment by jackd** [comment]
@spydon again I apologise for my android noobishness, but that doesn't have an `android` folder, let alone a `MainActivity.kt`. I've tried adding support through the flutter CLI and using the default `MainActivity.kt` and the replacement from the [README.md](https://github.com/flame-engine/gamepads?tab=readme-ov-file#android-integration) but have had no luck.

Could you provide build steps? I'm coming from a flutter for web background, and so maybe I'm just missing a `flutter pub get` equivalent command...

**Comment by spydon** [comment]
@jackd you must run `flutter create --platform =android .` first to get the platform directory.

**Comment by jackd** [comment]
@spydon yep, got that far. My question is about the changes to `MainActivity.kt` that are documented in the readme.

**Comment by spydon** [comment]
@markvideon maybe you can assist? I've never actually run it on android yet. 😅

**Comment by markvideon** [comment]
To clone the gamepads repo, navigate to the example project, and locally create an android project to build & run it I ran this command: 

```
git clone https://github.com/flame-engine/gamepads.git && cd gamepads/packages/gamepads/example/ && flutter create . --platforms=android && flutter pub add gamepads
```

If I were to build and run at this point, it would fail because changes to MainActivity.kt are required. I use the excerpt from [the project README](https://pub.dev/packages/gamepads_android), copying everything below the first line (as the stock MainActivity.kt already contains a line defining the name of the package. For the gamepads example project my adjusted MainActivity.kt file looks like this:

```

package com.example.example

import android.hardware.input.InputManager
import android.os.Handler
import android.view.InputDevice
import android.view.KeyEvent
import android.view.MotionEvent
import io.flutter.embedding.android.FlutterActivity
import org.flame_engine.gamepads_android.GamepadsCompatibleActivity

class MainActivity: FlutterActivity(), GamepadsCompatibleActivity {
    var keyListener: ((KeyEvent) -> Boolean)? = null
    var motionListener: ((MotionEvent) -> Boolean)? = null

    override fun dispatchGenericMotionEvent(motionEvent: MotionEvent): Boolean {
        return motionListener?.invoke(motionEvent) ?: false
    }

    override fun dispatchKeyEvent(keyEvent: KeyEvent): Boolean {
        return keyListener?.invoke(keyEvent) ?: false
    }

    override fun registerInputDeviceListener(
        listener: InputManager.InputDeviceListener, handler: Handler?) {
        val inputManager = getSystemService(INPUT_SERVICE) as InputManager
        inputManager.registerInputDeviceListener(listener, null)
    }

    override fun registerKeyEventHandler(handler: (KeyEvent) -> Boolean) {
        keyListener = handler
    }

    override fun registerMotionEventHandler(handler: (MotionEvent) -> Boolean) {
        motionListener = handler
    }
}
```

**Comment by markvideon** [comment]
To clone the gamepads repo, navigate to the example project, and locally create an android project to build & run it I ran this command: 

```
git clone https://github.com/flame-engine/gamepads.git && cd gamepads/packages/gamepads/example/ && flutter create . --platforms=android && flutter pub add gamepads
```

If I were to build and run at this point, it would fail because changes to MainActivity.kt are required. I use the excerpt from [the project README](https://pub.dev/packages/gamepads_android), copying everything below the first line (as the stock MainActivity.kt already contains a line defining the name of the package. For the gamepads example project my adjusted MainActivity.kt file looks like this:

```

package com.example.example

import android.hardware.input.InputManager
import android.os.Handler
import android.view.InputDevice
import android.view.KeyEvent
import android.view.MotionEvent
import io.flutter.embedding.android.FlutterActivity
import org.flame_engine.gamepads_android.GamepadsCompatibleActivity

class MainActivity: FlutterActivity(), GamepadsCompatibleActivity {
    var keyListener: ((KeyEvent) -> Boolean)? = null
    var motionListener: ((MotionEvent) -> Boolean)? = null

    override fun dispatchGenericMotionEvent(motionEvent: MotionEvent): Boolean {
        return motionListener?.invoke(motionEvent) ?: false
    }

    override fun dispatchKeyEvent(keyEvent: KeyEvent): Boolean {
        return keyListener?.invoke(keyEvent) ?: false
    }

    override fun registerInputDeviceListener(
        listener: InputManager.InputDeviceListener, handler: Handler?) {
        val inputManager = getSystemService(INPUT_SERVICE) as InputManager
        inputManager.registerInputDeviceListener(listener, null)
    }

    override fun registerKeyEventHandler(handler: (KeyEvent) -> Boolean) {
        keyListener = handler
    }

    override fun registerMotionEventHandler(handler: (MotionEvent) -> Boolean) {
        motionListener = handler
    }
}
```

With this, I am able to build and run and the package works as I expect. 

If you are unable to replicate this, it would be helpful to know how you've integrated gamepads into your project - can you share the relevant lines from your flutter project's pubspec.yaml file?

**Comment by jackd** [comment]
My apologies, it seems I was experimenting with this as a system update introduced a gradle/java inconsistency or... something. This had nothing to do with gamepads - I couldn't even build the starter counter app. Resolved with steps equivalent to discussed [here](https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide).

Thank you for your time.
